name: Test R package

on: [push, pull_request]

jobs:
  R_build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        r-version: ['4.4.1']
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
        working-directory: R/atlasapprox

    - name: Check R packages
      uses: r-lib/actions/check-r-package@v2
      with:
        error-on: '"note"'
        working-directory: R/atlasapprox
    
    - name: Build package (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        R.exe CMD build .
      working-directory: R/atlasapprox

    - name: Build R package (other systems)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        R CMD build .
      working-directory: R/atlasapprox


    - name: Run R CMD check --as-cran
      shell: bash
      run: |
        R CMD check --as-cran *.tar.gz
      working-directory: R/atlasapprox
